### ISSUE TITLE
Add functionality from #10 to TS branch

### ISSUE THREAD

**Issue by connertennery** [connertennery/Notion-to-Obsidian-Converter#11]
Functionality was added to fix #10 in the `main` branch that doesn't exist in the TS branch. Rewrite it with TS functions.

**Comment by dummifiedme** [comment]
![image](https://user-images.githubusercontent.com/68785729/97760732-d967ce00-1b29-11eb-8b89-cc22d9ce4e14.png)
It's throwing this error, right when I run `node main`

**Comment by dummifiedme** [comment]
Sorry to pester you again :) 
I am getting the following error.
I ran the old main.js it worked fine (not the table linking, but ran)
```
PS C:\Users\ DummyMe\Desktop\New folder> node main
Notion Export Path:
A
readline.js:1147
            throw err;
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.readdirSync (fs.js:950:10)
    at fixNotionExport (C:\Users\ DummyMe\Desktop\New folder\main.js:200:28)
    at C:\Users\ DummyMe\Desktop\New folder\main.js:239:17
    at Array.forEach (<anonymous>)
    at fixNotionExport (C:\Users\ DummyMe\Desktop\New folder\main.js:238:14)
    at C:\Users\ DummyMe\Desktop\New folder\main.js:11:17
    at Interface._onLine (readline.js:327:5)
    at Interface._line (readline.js:658:8)
    at Interface._ttyWrite (readline.js:1003:14)
    at ReadStream.onkeypress (readline.js:205:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by connertennery** [comment]
@dummifiedme That is a separate problem from this issue. I'll make a new issue for that.

**Comment by connertennery** [comment]
Closing this issue because the TS branch is out of date and needs to be written from scratch.
